### ISSUE TITLE
Sublime 3 .tmp files triggering remote Remove action

### ISSUE THREAD

**Issue by thisislawatts** [csaunders/themekit#28]
```zsh
Recieved Update event on 'snippets/.subl7ee.tmp'
Recieved Update event on 'snippets/collection-grid-item.liquid'
Successfully performed Update operation for file snippets/collection-grid-item.liquid to waitandsee.myshopify.com
Recieved Remove event on 'snippets/collection-grid-item.liquid'
Successfully performed Remove operation for file snippets/collection-grid-item.liquid to waitandsee.myshopify.com
```

If you [disable atomic saving](http://stackoverflow.com/questions/20634684/what-is-sublime-text-doing-when-i-save-a-file) it will no longer delete the file.
```zsh
Recieved Update event on 'snippets/collection-grid-item.liquid'
Successfully performed Update operation for file snippets/collection-grid-item.liquid to waitandsee.myshopify.com
```

By default `atomic_saving` is set as true, so I thought it may be worth noting this bug somewhere Google might find it .

**Comment by csaunders** [comment]
You could add `*.tmp` to your ignores and it won't get picked up by the watcher.

**Comment by thisislawatts** [comment]
Ah, I wasn't sure about that. Should I be referencing the config.yml structure from the [Shopify_theme](https://github.com/shopify/shopify_theme) gem?

**Comment by csaunders** [comment]
I believe you can. I've got a few minor features to get completed then I'll put some effort into improving the documentation. It's really bad at the moment :(

**Comment by csaunders** [comment]
@thisislawatts I've updated the docs and even have a website that doesn't look super terrible now. Does this help explain things a bit better?

http://themekit.cat/docs/

**Comment by thisislawatts** [comment]
That's looking great, thanks for following up on this.
