### ISSUE TITLE
uploading theme liquid file not working

### ISSUE THREAD

**Issue by bman-80stees** [csaunders/themekit#47]
I was in the middle of updating a bunch of theme files and everyone I uploaded worked just fine except for the theme.liquid file.
I'm using a Windows7 cmd to upload the files to our Shopify store.

```theme upload layout\theme.liquid``` doesn't work
```theme upload templates\index.liquid``` does work

Any thoughts on why this is acting this way?

**Comment by csaunders** [comment]
Do other uploads cause output to the terminal or are you just seeing no output? The best way to verify that nothing is happening would be to put something obvious in the template (like `<!-- i like turtles -->`) then verify that the changes aren't up on shopify via the admin.

I might not just be logging the event. Still a bug, but not as serious :)

**Comment by bman-80stees** [comment]
I put a very vivid color bar at the top of the <body> in the file and tried to upload it multiple times. It looks like it works each time within the cmd prompt, but when  I view the site, there is not change, no vivid bar at the very top. I also looked in the admin, no changes there either.

**Comment by bman-80stees** [comment]
There were also some really big css removals in the ```<head>``` section. That are not present after uploading the file via cmd.

**Comment by bman-80stees** [comment]
To answer your question after I type ```theme upload templates\index.liquid``` and hit enter, there is no output, just the prompt again. That file uploads fine. It does the same for the theme.liquid file, no output on the cmd window.

**Comment by bman-80stees** [comment]
I even tried closing out the cmd prompt and reinstalling the theme kit after a fresh download. That didn't work either.

**Comment by csaunders** [comment]
If you are on the latest version, re-installing wouldn't do anything. I can probably replicate this on my system and figure out whats going on via `mitmproxy`

**Comment by bman-80stees** [comment]
Apparently, I had a liquid syntax issue and that's why it didn't upload. Basically, Shopify rejected it, but in no way was I alerted of it. I found this out by taking the contents of my file and pasting them into the online editor and hitting save. That gave me an error in the admin theme editor. I fixed the error and tried the uploader again, this time it worked. Could there be some messaging to let us know if it was successful or there was an issue when uploading files? Right now, there is nothing at all, you just get a new line after a couple of seconds. This is the same if you don't specify the path correctly, too. Such as ```theme upload layouts\theme.liquid``` or ```theme upload assest\styles.css.liquid```

**Comment by csaunders** [comment]
Ah yeah... barf. I'll improve console reporting so you can see the status of an upload in your console instead of guessing that all was well.

**Comment by csaunders** [comment]
[0.2.3](https://github.com/csaunders/themekit/releases/tag/v0.2.3) adds output so you'll be able to tell if nothing is legitimately happening now. It'll also tell you if there was an error. If this isn't the case, please feel free to reopen the issue.
