### ISSUE TITLE
Not creating configuration file on OS X?

### ISSUE THREAD

**Issue by benje** [csaunders/themekit#52]
Hi there,
Just thought I'd give this tool a go (no pub intended!) to make uploading themes a bit quicker. I've installed it ( v0.2.3 darwin-amd64.zip) following the instructions and can see the command list using 'theme --help' as expected. However when I run:
    theme configure <private access token> store.myshopify.com staging
It does not return anything or create a config.yml file in my current directory. 
Any idea what i'm going wrong? thanks!

**Comment by csaunders** [comment]
The arguments aren't the same as they were in the theme gem. They are a bit more explicit. You can find out details about the subcommands by typing in `--help`:

```
> theme configure -h
Usage of theme configure:
  -access_token="": accessToken (or password) to make successful API calls
  -bucketSize=40: leaky bucket capacity
  -dir="/Users/csaunders/development": directory to create config.yml
  -domain="": your myshopify domain
  -env="development": environment for this configuration
  -refillRate=2: leaky bucket refill rate / second
```

For a basic configuration you'd need to set the `domain` and `access_token` flags. Looking at what you are wanting to do, you probably want to set the `env` flag as well.
