### ISSUE TITLE
Documentation needs a lot of work

### ISSUE THREAD

**Issue by sinak** [csaunders/themekit#57]
I'm relatively competent (though with minimal experience with go) but couldn't get themekit working, no matter what I tried. The documentation really needs better real-world examples.

I tried running:
```
theme configure -domain="domain.myshopify.com" -env="production" -access_token="secret"
```
But no configuration file was generated, and nor was there any error. Pretty stumped from there on out.

**Comment by csaunders** [comment]
It's broken, that's why it's not working. Must've been something brought in by the latest release. I'll get a regression test written up and figure out what broke.

An older version _should_ work.

**Comment by sinak** [comment]
Okay thanks @csaunders :). Glad to know I wasn't just doing it wrong.

**Comment by csaunders** [comment]
You can download a patched version here:

- https://github.com/csaunders/themekit/releases/tag/0.2.5
