### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by ajmalafif** [csaunders/themekit#61]
I've been trying to work on existing projects but themekit is blocking. I've set up everything as per docs but still can't manage to upload/download any files. It keeps on giving this error code:

```
2015/08/11 13:29:54 json: cannot unmarshal string into Go value of type []themekit.Asset
```
So how do I uninstall?

**Comment by ajmalafif** [comment]
I am still stuck with this issue and just need help to uninstall. Please advise.

**Comment by ajmalafif** [comment]
Found it. Just do `source theme`

and delete the repo. Thanks!

**Comment by markmakes** [comment]
`source theme` just returns a lot of parse errors, is there a new way to uninstall?

**Comment by pkavanaghjr** [comment]
ive got the same issue as @markmakes 

Is there a better way to uninstall?

**Comment by tanema** [comment]
If you installed using our install script you can delete the folder `~/.themekit` or you can run `rm $(which theme)`
